import { Client } from 'minio'

// Ensure we don't initialize multiple clients in development (hot-reloading)
const globalForMinio = global as unknown as { minioClient: Client }

// For production (Railway), always connect locally to the MinIO server running in the same container.
// For local dev, allow environment variables or fallback to localhost.
const isProd = process.env.NODE_ENV === 'production'

export const minioClient =
  globalForMinio.minioClient ||
  new Client({
    endPoint: isProd ? '127.0.0.1' : (process.env.MINIO_ENDPOINT || 'localhost'),
    port: isProd ? 9000 : (process.env.MINIO_PORT ? parseInt(process.env.MINIO_PORT) : 9000),
    useSSL: isProd ? false : (process.env.MINIO_USE_SSL === 'true'),
    accessKey: process.env.MINIO_ACCESS_KEY || 'myfilesadmin',
    secretKey: process.env.MINIO_SECRET_KEY || 'myfilespassword123',
    region: process.env.MINIO_REGION || 'ap-southeast-1',
    pathStyle: true,
  })

if (process.env.NODE_ENV !== 'production') globalForMinio.minioClient = minioClient

export const BUCKET_NAME = process.env.MINIO_BUCKET_NAME || 'myfiles-bucket'

// Initialize the bucket if it doesn't exist
export async function initializeMinio() {
  try {
    const exists = await minioClient.bucketExists(BUCKET_NAME)
    if (!exists) {
      await minioClient.makeBucket(BUCKET_NAME, process.env.MINIO_REGION || 'ap-southeast-1')
      console.log(`Bucket ${BUCKET_NAME} created successfully.`)

      // Set bucket policy to allow public read, since we might use presigned URLs or direct links
      // Actually, for a secure sharing app, we should NOT set public read policy.
      // We will rely strictly on presigned URLs generated by the backend when the correct passkey is provided.
    }
  } catch (error) {
    console.error('Error initializing MinIO:', error)
  }
}


