import { Client } from "minio";

// Ensure we don't initialize multiple clients in development (hot-reloading)
const globalForMinio = global as unknown as { minioClient: Client };

function getMinioConfig() {
  const rawEndpoint = process.env.MINIO_ENDPOINT?.trim();
  const normalizedUrl = rawEndpoint
    ? rawEndpoint.replace(/^https?:\/\//, "").replace(/\/+$/, "")
    : undefined;

  const hasExplicitPort =
    normalizedUrl?.includes(":") &&
    !normalizedUrl.startsWith("[") &&
    normalizedUrl.split(":").length > 1;

  const endPoint = normalizedUrl?.split(":")[0] || "localhost";
  const port = process.env.MINIO_PORT
    ? parseInt(process.env.MINIO_PORT, 10)
    : hasExplicitPort
      ? parseInt(normalizedUrl!.split(":")[1], 10)
      : 9000;
  const useSSL =
    process.env.MINIO_USE_SSL === "true" ||
    rawEndpoint?.startsWith("https://") ||
    false;

  return {
    endPoint,
    port,
    useSSL,
  };
}

const { endPoint, port, useSSL } = getMinioConfig();

export const minioClient =
  globalForMinio.minioClient ||
  new Client({
    endPoint,
    port,
    useSSL,
    accessKey: process.env.MINIO_ACCESS_KEY || "myfilesadmin",
    secretKey: process.env.MINIO_SECRET_KEY || "myfilespassword123",
    region: process.env.MINIO_REGION || "ap-southeast-1",
    pathStyle: true,
  });

if (process.env.NODE_ENV !== "production")
  globalForMinio.minioClient = minioClient;

export const BUCKET_NAME = process.env.MINIO_BUCKET_NAME || "myfiles-bucket";

// Initialize the bucket if it doesn't exist
export async function initializeMinio() {
  try {
    const exists = await minioClient.bucketExists(BUCKET_NAME);
    if (!exists) {
      await minioClient.makeBucket(
        BUCKET_NAME,
        process.env.MINIO_REGION || "ap-southeast-1",
      );
      console.log(`Bucket ${BUCKET_NAME} created successfully.`);

      // Set bucket policy to allow public read, since we might use presigned URLs or direct links
      // Actually, for a secure sharing app, we should NOT set public read policy.
      // We will rely strictly on presigned URLs generated by the backend when the correct passkey is provided.
    }
  } catch (error) {
    console.error("Error initializing MinIO:", error);
  }
}
