import { Client } from 'minio'

// Ensure we don't initialize multiple clients in development (hot-reloading)
const globalForMinio = global as unknown as { minioClient: Client }

export const minioClient =
  globalForMinio.minioClient ||
  new Client({
    endPoint: process.env.MINIO_ENDPOINT || 'localhost',
    port: parseInt(process.env.MINIO_PORT || '9000'),
    useSSL: process.env.MINIO_USE_SSL === 'true',
    accessKey: process.env.MINIO_ACCESS_KEY || 'myfilesadmin',
    secretKey: process.env.MINIO_SECRET_KEY || 'myfilespassword123',
  })

if (process.env.NODE_ENV !== 'production') globalForMinio.minioClient = minioClient

export const BUCKET_NAME = process.env.MINIO_BUCKET_NAME || 'myfiles-bucket'

// Initialize the bucket if it doesn't exist
export async function initializeMinio() {
  try {
    const exists = await minioClient.bucketExists(BUCKET_NAME)
    if (!exists) {
      await minioClient.makeBucket(BUCKET_NAME, 'us-east-1')
      console.log(`Bucket ${BUCKET_NAME} created successfully.`)

      // Set bucket policy to allow public read, since we might use presigned URLs or direct links
      // Actually, for a secure sharing app, we should NOT set public read policy.
      // We will rely strictly on presigned URLs generated by the backend when the correct passkey is provided.
    }
  } catch (error) {
    console.error('Error initializing MinIO:', error)
  }
}
